[server]
port=8080
debug=false
zeus_dns="0.0.0.0:3001"
zeus_admin_token="bock-gaudy-projector-steer-selection-fiber"
env="development"
log_dir="/Users/dale/go/src/gitee.com/dalezhang/account_center/tmp/log/"

[pg]
host="localhost"
port=54320
user="postgres"
password="postgres"
dbname="account_center_test"

[mysql]
host="localhost"
port=33061
user="root"
password="root"
dbname="arc-warden_test"


[redis]
host="localhost"
port=6379

[jwt]
secret="yockii"

[rsa]
public_key_path="conf/rsa/server_rsa_public_key.pem"
private_key_path="conf/rsa/server_rsa_private_key.pem"